test_that("the alpha interval reads cuts deeper than the stored profile trace", {
  skip_on_cran()
  set.seed(31); x <- rnorm(250)
  d <- data.frame(y = rcpb(250, exp(1.5 + 0.4 * x), 0.5, truncated = TRUE), x = x)
  fit <- cpb(y ~ x, d, se = "none")
  ci95 <- alpha_confint(fit)
  ## the stored trace stops 4 log-likelihood units below the maximum; a 99.9% cut sits 5.4 below it and used to
  ## be reported as a one-sided interval (0.005, 0.999)
  ci999 <- alpha_confint(fit, level = 0.999)
  expect_false(isTRUE(attr(ci999, "boundary")))
  expect_gt(ci999[["lower"]], 0.005); expect_lt(ci999[["upper"]], 0.999)
  expect_lt(ci999[["lower"]], ci95[["lower"]]); expect_gt(ci999[["upper"]], ci95[["upper"]])
  expect_true(ci95[["lower"]] < fit$alpha && fit$alpha < ci95[["upper"]])
})

test_that("side-specific cuts move each limit on its own", {
  skip_on_cran()
  set.seed(32); x <- rnorm(250)
  d <- data.frame(y = rcpb(250, exp(1.5 + 0.4 * x), 0.5, truncated = TRUE), x = x)
  fit <- cpb(y ~ x, d, se = "none")
  base <- underdisp:::.cpb_alpha_profile_ci(fit)
  same <- underdisp:::.cpb_alpha_profile_ci(fit, drops = rep(qchisq(0.95, 1) / 2, 2))
  expect_equal(same, base)
  wide_up <- underdisp:::.cpb_alpha_profile_ci(fit, drops = c(qchisq(0.95, 1) / 2, 3.4))
  expect_equal(wide_up[["lower"]], base[["lower"]], tolerance = 1e-3)
  expect_gt(wide_up[["upper"]], base[["upper"]])
  none <- underdisp:::.cpb_alpha_profile_ci(fit, drops = c(0, 0))
  expect_equal(none[["lower"]], unname(fit$alpha), tolerance = 1e-3)
  expect_equal(none[["upper"]], unname(fit$alpha), tolerance = 1e-3)
})
