// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpb_fe_nll_cpp
double cpb_fe_nll_cpp(NumericVector params, NumericMatrix X, IntegerVector Y, NumericVector offset, IntegerVector ustart, int n_units, int max_support, bool truncated, int inner_it);
RcppExport SEXP _underdisp_cpb_fe_nll_cpp(SEXP paramsSEXP, SEXP XSEXP, SEXP YSEXP, SEXP offsetSEXP, SEXP ustartSEXP, SEXP n_unitsSEXP, SEXP max_supportSEXP, SEXP truncatedSEXP, SEXP inner_itSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ustart(ustartSEXP);
    Rcpp::traits::input_parameter< int >::type n_units(n_unitsSEXP);
    Rcpp::traits::input_parameter< int >::type max_support(max_supportSEXP);
    Rcpp::traits::input_parameter< bool >::type truncated(truncatedSEXP);
    Rcpp::traits::input_parameter< int >::type inner_it(inner_itSEXP);
    rcpp_result_gen = Rcpp::wrap(cpb_fe_nll_cpp(params, X, Y, offset, ustart, n_units, max_support, truncated, inner_it));
    return rcpp_result_gen;
END_RCPP
}
// cpb_fe_intercepts_cpp
NumericVector cpb_fe_intercepts_cpp(NumericVector params, NumericMatrix X, IntegerVector Y, NumericVector offset, IntegerVector ustart, int n_units, int max_support, bool truncated, int inner_it);
RcppExport SEXP _underdisp_cpb_fe_intercepts_cpp(SEXP paramsSEXP, SEXP XSEXP, SEXP YSEXP, SEXP offsetSEXP, SEXP ustartSEXP, SEXP n_unitsSEXP, SEXP max_supportSEXP, SEXP truncatedSEXP, SEXP inner_itSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ustart(ustartSEXP);
    Rcpp::traits::input_parameter< int >::type n_units(n_unitsSEXP);
    Rcpp::traits::input_parameter< int >::type max_support(max_supportSEXP);
    Rcpp::traits::input_parameter< bool >::type truncated(truncatedSEXP);
    Rcpp::traits::input_parameter< int >::type inner_it(inner_itSEXP);
    rcpp_result_gen = Rcpp::wrap(cpb_fe_intercepts_cpp(params, X, Y, offset, ustart, n_units, max_support, truncated, inner_it));
    return rcpp_result_gen;
END_RCPP
}
// cpb_nll_cpp
double cpb_nll_cpp(NumericVector params, NumericMatrix X, IntegerVector Y, NumericVector offset, int max_support, bool truncated);
RcppExport SEXP _underdisp_cpb_nll_cpp(SEXP paramsSEXP, SEXP XSEXP, SEXP YSEXP, SEXP offsetSEXP, SEXP max_supportSEXP, SEXP truncatedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< int >::type max_support(max_supportSEXP);
    Rcpp::traits::input_parameter< bool >::type truncated(truncatedSEXP);
    rcpp_result_gen = Rcpp::wrap(cpb_nll_cpp(params, X, Y, offset, max_support, truncated));
    return rcpp_result_gen;
END_RCPP
}
// cpb_wnll_cpp
double cpb_wnll_cpp(NumericVector params, NumericMatrix X, IntegerVector Y, NumericVector w, NumericVector offset, int max_support, bool truncated);
RcppExport SEXP _underdisp_cpb_wnll_cpp(SEXP paramsSEXP, SEXP XSEXP, SEXP YSEXP, SEXP wSEXP, SEXP offsetSEXP, SEXP max_supportSEXP, SEXP truncatedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< int >::type max_support(max_supportSEXP);
    Rcpp::traits::input_parameter< bool >::type truncated(truncatedSEXP);
    rcpp_result_gen = Rcpp::wrap(cpb_wnll_cpp(params, X, Y, w, offset, max_support, truncated));
    return rcpp_result_gen;
END_RCPP
}
// cpb_lp0_cpp
NumericMatrix cpb_lp0_cpp(NumericVector params, NumericMatrix X, IntegerVector Y, NumericVector offset, int max_support, bool truncated);
RcppExport SEXP _underdisp_cpb_lp0_cpp(SEXP paramsSEXP, SEXP XSEXP, SEXP YSEXP, SEXP offsetSEXP, SEXP max_supportSEXP, SEXP truncatedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< int >::type max_support(max_supportSEXP);
    Rcpp::traits::input_parameter< bool >::type truncated(truncatedSEXP);
    rcpp_result_gen = Rcpp::wrap(cpb_lp0_cpp(params, X, Y, offset, max_support, truncated));
    return rcpp_result_gen;
END_RCPP
}
// gec_fe_nll_cpp
double gec_fe_nll_cpp(NumericVector params, NumericMatrix X, IntegerVector Y, NumericVector offset, IntegerVector ustart, int n_units, int max_support, int inner_it);
RcppExport SEXP _underdisp_gec_fe_nll_cpp(SEXP paramsSEXP, SEXP XSEXP, SEXP YSEXP, SEXP offsetSEXP, SEXP ustartSEXP, SEXP n_unitsSEXP, SEXP max_supportSEXP, SEXP inner_itSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ustart(ustartSEXP);
    Rcpp::traits::input_parameter< int >::type n_units(n_unitsSEXP);
    Rcpp::traits::input_parameter< int >::type max_support(max_supportSEXP);
    Rcpp::traits::input_parameter< int >::type inner_it(inner_itSEXP);
    rcpp_result_gen = Rcpp::wrap(gec_fe_nll_cpp(params, X, Y, offset, ustart, n_units, max_support, inner_it));
    return rcpp_result_gen;
END_RCPP
}
// gec_fe_intercepts_cpp
NumericVector gec_fe_intercepts_cpp(NumericVector params, NumericMatrix X, IntegerVector Y, NumericVector offset, IntegerVector ustart, int n_units, int max_support, int inner_it);
RcppExport SEXP _underdisp_gec_fe_intercepts_cpp(SEXP paramsSEXP, SEXP XSEXP, SEXP YSEXP, SEXP offsetSEXP, SEXP ustartSEXP, SEXP n_unitsSEXP, SEXP max_supportSEXP, SEXP inner_itSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ustart(ustartSEXP);
    Rcpp::traits::input_parameter< int >::type n_units(n_unitsSEXP);
    Rcpp::traits::input_parameter< int >::type max_support(max_supportSEXP);
    Rcpp::traits::input_parameter< int >::type inner_it(inner_itSEXP);
    rcpp_result_gen = Rcpp::wrap(gec_fe_intercepts_cpp(params, X, Y, offset, ustart, n_units, max_support, inner_it));
    return rcpp_result_gen;
END_RCPP
}
// gec_nll_cpp
double gec_nll_cpp(NumericVector params, NumericMatrix X, IntegerVector Y, NumericVector offset, int max_support);
RcppExport SEXP _underdisp_gec_nll_cpp(SEXP paramsSEXP, SEXP XSEXP, SEXP YSEXP, SEXP offsetSEXP, SEXP max_supportSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< int >::type max_support(max_supportSEXP);
    rcpp_result_gen = Rcpp::wrap(gec_nll_cpp(params, X, Y, offset, max_support));
    return rcpp_result_gen;
END_RCPP
}
// gec_lp0_cpp
NumericMatrix gec_lp0_cpp(NumericVector params, NumericMatrix X, IntegerVector Y, NumericVector offset, int max_support);
RcppExport SEXP _underdisp_gec_lp0_cpp(SEXP paramsSEXP, SEXP XSEXP, SEXP YSEXP, SEXP offsetSEXP, SEXP max_supportSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< int >::type max_support(max_supportSEXP);
    rcpp_result_gen = Rcpp::wrap(gec_lp0_cpp(params, X, Y, offset, max_support));
    return rcpp_result_gen;
END_RCPP
}
// gec_pmf_cpp
NumericMatrix gec_pmf_cpp(NumericVector mu, double delta, int kmax, int max_support);
RcppExport SEXP _underdisp_gec_pmf_cpp(SEXP muSEXP, SEXP deltaSEXP, SEXP kmaxSEXP, SEXP max_supportSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< int >::type kmax(kmaxSEXP);
    Rcpp::traits::input_parameter< int >::type max_support(max_supportSEXP);
    rcpp_result_gen = Rcpp::wrap(gec_pmf_cpp(mu, delta, kmax, max_support));
    return rcpp_result_gen;
END_RCPP
}
// gec_mean_cpp
NumericVector gec_mean_cpp(NumericVector mu, double delta, int max_support);
RcppExport SEXP _underdisp_gec_mean_cpp(SEXP muSEXP, SEXP deltaSEXP, SEXP max_supportSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< int >::type max_support(max_supportSEXP);
    rcpp_result_gen = Rcpp::wrap(gec_mean_cpp(mu, delta, max_support));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_underdisp_cpb_fe_nll_cpp", (DL_FUNC) &_underdisp_cpb_fe_nll_cpp, 9},
    {"_underdisp_cpb_fe_intercepts_cpp", (DL_FUNC) &_underdisp_cpb_fe_intercepts_cpp, 9},
    {"_underdisp_cpb_nll_cpp", (DL_FUNC) &_underdisp_cpb_nll_cpp, 6},
    {"_underdisp_cpb_wnll_cpp", (DL_FUNC) &_underdisp_cpb_wnll_cpp, 7},
    {"_underdisp_cpb_lp0_cpp", (DL_FUNC) &_underdisp_cpb_lp0_cpp, 6},
    {"_underdisp_gec_fe_nll_cpp", (DL_FUNC) &_underdisp_gec_fe_nll_cpp, 8},
    {"_underdisp_gec_fe_intercepts_cpp", (DL_FUNC) &_underdisp_gec_fe_intercepts_cpp, 8},
    {"_underdisp_gec_nll_cpp", (DL_FUNC) &_underdisp_gec_nll_cpp, 5},
    {"_underdisp_gec_lp0_cpp", (DL_FUNC) &_underdisp_gec_lp0_cpp, 5},
    {"_underdisp_gec_pmf_cpp", (DL_FUNC) &_underdisp_gec_pmf_cpp, 4},
    {"_underdisp_gec_mean_cpp", (DL_FUNC) &_underdisp_gec_mean_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_underdisp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
