# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cmp_loglambda_cpp <- function(mu, nu) {
    .Call(`_underdisp_cmp_loglambda_cpp`, mu, nu)
}

cmp_logZ_cpp <- function(loglambda, nu) {
    .Call(`_underdisp_cmp_logZ_cpp`, loglambda, nu)
}

cmp_moments_cpp <- function(loglambda, nu) {
    .Call(`_underdisp_cmp_moments_cpp`, loglambda, nu)
}

cpb_fe_nll_cpp <- function(params, X, Y, offset, w, ustart, n_units, max_support, truncated, inner_it, awarm) {
    .Call(`_underdisp_cpb_fe_nll_cpp`, params, X, Y, offset, w, ustart, n_units, max_support, truncated, inner_it, awarm)
}

cpb_fe_grad_cpp <- function(params, X, Y, offset, w, ustart, n_units, max_support, truncated, a, edge) {
    .Call(`_underdisp_cpb_fe_grad_cpp`, params, X, Y, offset, w, ustart, n_units, max_support, truncated, a, edge)
}

cpb_dlogpmf_cpp <- function(y, lam, alpha, max_support, truncated) {
    .Call(`_underdisp_cpb_dlogpmf_cpp`, y, lam, alpha, max_support, truncated)
}

cpb_fe_intercepts_cpp <- function(params, X, Y, offset, w, ustart, n_units, max_support, truncated, inner_it) {
    .Call(`_underdisp_cpb_fe_intercepts_cpp`, params, X, Y, offset, w, ustart, n_units, max_support, truncated, inner_it)
}

cpb_nll_cpp <- function(params, X, Y, offset, max_support, truncated) {
    .Call(`_underdisp_cpb_nll_cpp`, params, X, Y, offset, max_support, truncated)
}

cpb_wnll_cpp <- function(params, X, Y, w, offset, max_support, truncated) {
    .Call(`_underdisp_cpb_wnll_cpp`, params, X, Y, w, offset, max_support, truncated)
}

cpb_lp0_cpp <- function(params, X, Y, offset, max_support, truncated) {
    .Call(`_underdisp_cpb_lp0_cpp`, params, X, Y, offset, max_support, truncated)
}

dp_norm_cpp <- function(mu, theta, cap) {
    .Call(`_underdisp_dp_norm_cpp`, mu, theta, cap)
}

gp_norm_cpp <- function(mu, lambda, cap) {
    .Call(`_underdisp_gp_norm_cpp`, mu, lambda, cap)
}

gec_fe_nll_cpp <- function(params, X, Y, offset, w, ustart, n_units, max_support, inner_it, awarm) {
    .Call(`_underdisp_gec_fe_nll_cpp`, params, X, Y, offset, w, ustart, n_units, max_support, inner_it, awarm)
}

gec_fe_grad_cpp <- function(params, X, Y, offset, w, ustart, n_units, max_support, a, edge) {
    .Call(`_underdisp_gec_fe_grad_cpp`, params, X, Y, offset, w, ustart, n_units, max_support, a, edge)
}

gec_fe_intercepts_cpp <- function(params, X, Y, offset, w, ustart, n_units, max_support, inner_it) {
    .Call(`_underdisp_gec_fe_intercepts_cpp`, params, X, Y, offset, w, ustart, n_units, max_support, inner_it)
}

gec_nll_cpp <- function(params, X, Y, offset, max_support) {
    .Call(`_underdisp_gec_nll_cpp`, params, X, Y, offset, max_support)
}

gec_wnll_cpp <- function(params, X, Y, w, offset, max_support) {
    .Call(`_underdisp_gec_wnll_cpp`, params, X, Y, w, offset, max_support)
}

gec_lp0_cpp <- function(params, X, Y, offset, max_support) {
    .Call(`_underdisp_gec_lp0_cpp`, params, X, Y, offset, max_support)
}

gec_pmf_cpp <- function(mu, delta, kmax, max_support) {
    .Call(`_underdisp_gec_pmf_cpp`, mu, delta, kmax, max_support)
}

gec_klen_cpp <- function(mu, delta, max_support) {
    .Call(`_underdisp_gec_klen_cpp`, mu, delta, max_support)
}

gec_mean_cpp <- function(mu, delta, max_support) {
    .Call(`_underdisp_gec_mean_cpp`, mu, delta, max_support)
}

