# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpb_fe_nll_cpp <- function(params, X, Y, offset, ustart, n_units, max_support, truncated, inner_it) {
    .Call(`_underdisp_cpb_fe_nll_cpp`, params, X, Y, offset, ustart, n_units, max_support, truncated, inner_it)
}

cpb_fe_intercepts_cpp <- function(params, X, Y, offset, ustart, n_units, max_support, truncated, inner_it) {
    .Call(`_underdisp_cpb_fe_intercepts_cpp`, params, X, Y, offset, ustart, n_units, max_support, truncated, inner_it)
}

cpb_nll_cpp <- function(params, X, Y, offset, max_support, truncated) {
    .Call(`_underdisp_cpb_nll_cpp`, params, X, Y, offset, max_support, truncated)
}

cpb_wnll_cpp <- function(params, X, Y, w, offset, max_support, truncated) {
    .Call(`_underdisp_cpb_wnll_cpp`, params, X, Y, w, offset, max_support, truncated)
}

cpb_lp0_cpp <- function(params, X, Y, offset, max_support, truncated) {
    .Call(`_underdisp_cpb_lp0_cpp`, params, X, Y, offset, max_support, truncated)
}

gec_fe_nll_cpp <- function(params, X, Y, offset, ustart, n_units, max_support, inner_it) {
    .Call(`_underdisp_gec_fe_nll_cpp`, params, X, Y, offset, ustart, n_units, max_support, inner_it)
}

gec_fe_intercepts_cpp <- function(params, X, Y, offset, ustart, n_units, max_support, inner_it) {
    .Call(`_underdisp_gec_fe_intercepts_cpp`, params, X, Y, offset, ustart, n_units, max_support, inner_it)
}

gec_nll_cpp <- function(params, X, Y, offset, max_support) {
    .Call(`_underdisp_gec_nll_cpp`, params, X, Y, offset, max_support)
}

gec_lp0_cpp <- function(params, X, Y, offset, max_support) {
    .Call(`_underdisp_gec_lp0_cpp`, params, X, Y, offset, max_support)
}

gec_pmf_cpp <- function(mu, delta, kmax, max_support) {
    .Call(`_underdisp_gec_pmf_cpp`, mu, delta, kmax, max_support)
}

gec_mean_cpp <- function(mu, delta, max_support) {
    .Call(`_underdisp_gec_mean_cpp`, mu, delta, max_support)
}

